version: '3.7'

services:
  mongo:
    image: mongo:4.0.4
    container_name: payments_mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
  test-mongo:
    image: mongo:4.0.4
    container_name: payments_test-mongo
    restart: on-failure
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:root@mongo:27017
    depends_on:
      - mongo

volumes:
  data:
